In [1]:
import pprint
from databasemrg import StorageManager

pp = pprint.PrettyPrinter(indent=4, width=50)
stormrg = StorageManager("T03")

In [20]:
query_resultaat = stormrg.zoekBegrippen_algemeen(
    {
        "zoek_opdracht": "O"
    }
)

query_resultaat

[{'begrip_id': 1,
  'functie_naam': 'mario is coolL',
  'status_naam': 'Toad',
  'naam_begrippenkader': 'Toadjes_zijnCool',
  'begrip_code': 'Toad-001',
  'voorkeursterm': '1E voorkeursterm',
  'definitie_begrip': 'Uitleg ............... effwefqefwefwefqewfwef',
  'toelichting_begrip': 'toelichting_begrip ..........',
  'voorbeeld_begrip': 'voorbeeld_begrip . biorboiqhrebo qreoqierjgoiqerg',
  'aangemaakt_op': 'datum 1',
  'gewijzigd_op': 'datum 2',
  'vervalt_op': 'datum 3',
  'bron': 'https://toad.com'},
 {'begrip_id': 2,
  'functie_naam': 'mario is coolL',
  'status_naam': 'Geen Toad',
  'naam_begrippenkader': 'Yoshi',
  'begrip_code': 'Toad-001',
  'voorkeursterm': '1E voorkeursterm',
  'definitie_begrip': 'Uitleg ............... effwefqefwefwefqewfwef',
  'toelichting_begrip': 'toelichting_begrip ..........',
  'voorbeeld_begrip': 'voorbeeld_begrip . biorboiqhrebo qreoqierjgoiqerg',
  'aangemaakt_op': 'datum 1',
  'gewijzigd_op': 'datum 2',
  'vervalt_op': 'datum 3',
  'bron': 'https://toad.com'},
 {'begrip_id': 3,
  'functie_naam': 'mario is coolL',
  'status_naam': 'Geen Toad',
  'naam_begrippenkader': 'Yoshi',
  'begrip_code': 'Toad-001',
  'voorkeursterm': '2E voorkeursterm',
  'definitie_begrip': 'Uitleg ............... effwefqefwefwefqewfwef',
  'toelichting_begrip': 'toelichting_begrip ..........',
  'voorbeeld_begrip': 'voorbeeld_begrip . biorboiqhrebo qreoqierjgoiqerg',
  'aangemaakt_op': 'datum 1',
  'gewijzigd_op': 'datum 2',
  'vervalt_op': 'datum 3',
  'bron': 'https://toad.com'},
 {'begrip_id': 4,
  'functie_naam': 'mario is coolL',
  'status_naam': 'Geen Toad',
  'naam_begrippenkader': 'Mario',
  'begrip_code': 'Toad-001',
  'voorkeursterm': 'TOAD voorkeursterm',
  'definitie_begrip': 'fewefwefwefqewfwef',
  'toelichting_begrip': 'ER zijn geentoads.',
  'voorbeeld_begrip': 'Muzhroomzzz',
  'aangemaakt_op': 'datum 1',
  'gewijzigd_op': 'datum 2',
  'vervalt_op': 'datum 3',
  'bron': 'https://toad.com'},
 {'begrip_id': 5,
  'functie_naam': 'mario is coolL',
  'status_naam': 'Geen Toad',
  'naam_begrippenkader': 'Mario',
  'begrip_code': 'Toad-001',
  'voorkeursterm': 'Zoeken',
  'definitie_begrip': 'fewefwefwefqewfwef',
  'toelichting_begrip': 'ER zijn geentoads.',
  'voorbeeld_begrip': 'Muzhroomzzz',
  'aangemaakt_op': 'datum 1',
  'gewijzigd_op': 'datum 2',
  'vervalt_op': 'datum 3',
  'bron': 'https://toad.com'},
 {'begrip_id': 6,
  'functie_naam': 'mario is coolL',
  'status_naam': 'Geen Toad',
  'naam_begrippenkader': 'Mario',
  'begrip_code': 'Toad-001',
  'voorkeursterm': 'zoeken',
  'definitie_begrip': 'fewefwefwefqewfwef',
  'toelichting_begrip': 'ER zijn geentoads.',
  'voorbeeld_begrip': 'Muzhroomzzz',
  'aangemaakt_op': 'datum 1',
  'gewijzigd_op': 'datum 2',
  'vervalt_op': 'datum 3',
  'bron': 'https://toad.com'},
 {'begrip_id': 7,
  'functie_naam': 'mario is coolL',
  'status_naam': 'Geen Toad',
  'naam_begrippenkader': 'Mario',
  'begrip_code': 'Toad-001',
  'voorkeursterm': 'ACX',
  'definitie_begrip': 'XXC',
  'toelichting_begrip': 'ER zijn geentoads.',
  'voorbeeld_begrip': 'Muzhroomzzz',
  'aangemaakt_op': 'datum 1',
  'gewijzigd_op': 'datum 2',
  'vervalt_op': 'datum 3',
  'bron': 'https://toad.com'},
 {'begrip_id': 8,
  'functie_naam': 'mario is coolL',
  'status_naam': 'Geen Toad',
  'naam_begrippenkader': 'Yoshi',
  'begrip_code': 'Toad-001',
  'voorkeursterm': 'ACX',
  'definitie_begrip': 'XXC',
  'toelichting_begrip': 'ER zijn geentoads.',
  'voorbeeld_begrip': 'Muzhroomzzz',
  'aangemaakt_op': 'datum 1',
  'gewijzigd_op': 'datum 2',
  'vervalt_op': 'datum 3',
  'bron': 'https://toad.com'}]

In [54]:
%%sql
SELECT DISTINCT Functie.functie_naam, Status.status, Begrippenkader.naam_begrippenkader, Begrip_code.code,
                   Begrip.voorkeursterm, Begrip.definitie_begrip,  Begrip.toelichting_begrip,
                   Begrip.voorbeeld_begrip, Begrip.aangemaakt_op, Begrip.gewijzigd_op, Begrip.vervalt_op, Begrip.bron,
                   Begrip.begrip_id
            FROM Begrip
            FULL OUTER JOIN Functie ON Functie.functie_id = Begrip.FK_functie_id
            FULL OUTER JOIN Status ON Status.status_id = Begrip.FK_status_id
            FULL OUTER JOIN Begrippenkader ON Begrippenkader.begrippenkader_id = Begrip.FK_begrippenkader_id
            FULL OUTER JOIN Begrip_code ON Begrip_code.begrip_code_id = Begrip.FK_begrip_code_id
            FULL OUTER JOIN Alternatieve_term ON Begrip.begrip_id = Alternatieve_term.FK_begrip_id
            WHERE UPPER(Begrip.voorkeursterm )LIKE UPPER("%AA%")
                OR UPPER(Begrip.definitie_begrip) LIKE UPPER("%AA%")
                OR UPPER(Begrippenkader.naam_begrippenkader) LIKE UPPER("%AA%")
                OR UPPER(Alternatieve_term.alternatieve_term) LIKE UPPER("%AA%")
            ORDER BY Begrip.begrip_id

,functie_naam,status,naam_begrippenkader,code,voorkeursterm,definitie_begrip,toelichting_begrip,voorbeeld_begrip,aangemaakt_op,gewijzigd_op,vervalt_op,bron,begrip_id
0,mario is coolL,Geen Toad,Yoshi,Toad-001,BowserisToad,bowser,Bowser Bowser Bowser Bowser,Buzzhe,datum 1,datum 2,datum 3,https://toad.com,9

In [18]:
%%sql
SELECT Begrippenkader.begrippenkader_id, Functie.functie_naam, Status.status,
                   Begrippenkader.naam_begrippenkader, Begrippenkader.omschrijving, Begrippenkader.aangemaakt_op,
                   Begrippenkader.gewijzigd_op, Begrippenkader.vervalt_op
            FROM Begrippenkader
            JOIN Functie ON Functie.functie_id = Begrippenkader.FK_functie_id
            JOIN Status ON Status.status_id = Begrippenkader.FK_status_id

            ORDER BY Begrippenkader.begrippenkader_id

,begrippenkader_id,functie_naam,status,naam_begrippenkader,omschrijving,aangemaakt_op,gewijzigd_op,vervalt_op
0,1,mario is coolL,Geen Toad,Toadjes_zijnCool,Speciale Toads only,DATum1,Datum2,Datum3
1,2,mario is coolL,Geen Toad,Yoshi,Speciale Toads only,DATum1,Datum2,Datum3
2,3,mario is coolL,Geen Toad,Mario,SSFTR,DATum1,Datum2,Datum3

In [17]:
query_resultaat = stormrg.geefAlle_Begrippenkaders(
)

pp.pprint(query_resultaat)

[   {   'aangemaakt_op': 'DATum1',
        'begrippenkader_id': 1,
        'functie_naam': 'mario is coolL',
        'gewijzigd_op': 'Datum2',
        'naam_begrippenkader': 'Toadjes_zijnCool',
        'omshrijving': 'Speciale Toads only',
        'status_naam': 'Geen Toad',
        'vervalt_op': 'Datum3'},
    {   'aangemaakt_op': 'DATum1',
        'begrippenkader_id': 2,
        'functie_naam': 'mario is coolL',
        'gewijzigd_op': 'Datum2',
        'naam_begrippenkader': 'Yoshi',
        'omshrijving': 'Speciale Toads only',
        'status_naam': 'Geen Toad',
        'vervalt_op': 'Datum3'},
    {   'aangemaakt_op': 'DATum1',
        'begrippenkader_id': 3,
        'functie_naam': 'mario is coolL',
        'gewijzigd_op': 'Datum2',
        'naam_begrippenkader': 'Mario',
        'omshrijving': 'SSFTR',
        'status_naam': 'Geen Toad',
        'vervalt_op': 'Datum3'}]

In [4]:
%%sql
SELECT Functie.functie_naam, Status.status, Begrippenkader.naam_begrippenkader, Begrip_code.code,
                   Begrip.voorkeursterm, Begrip.definitie_begrip,  Begrip.toelichting_begrip,
                   Begrip.voorbeeld_begrip, Begrip.aangemaakt_op, Begrip.gewijzigd_op, Begrip.vervalt_op, Begrip.bron,
                   Begrip.begrip_id
            FROM Begrip
            JOIN Functie ON Functie.functie_id = Begrip.FK_functie_id
            JOIN Status ON Status.status_id = Begrip.FK_status_id
            JOIN Begrippenkader ON Begrippenkader.begrippenkader_id = Begrip.FK_begrippenkader_id
            JOIN Begrip_code ON Begrip_code.begrip_code_id = Begrip.FK_begrip_code_id
            WHERE Begrippenkader.naam_begrippenkader = "Mario"
            ORDER BY Begrip.begrip_id

,functie_naam,status,naam_begrippenkader,code,voorkeursterm,definitie_begrip,toelichting_begrip,voorbeeld_begrip,aangemaakt_op,gewijzigd_op,vervalt_op,bron,begrip_id
0,mario is coolL,Geen Toad,Mario,Toad-001,TOAD voorkeursterm,fewefwefwefqewfwef,ER zijn geentoads.,Muzhroomzzz,datum 1,datum 2,datum 3,https://toad.com,4
1,mario is coolL,Geen Toad,Mario,Toad-001,Zoeken,fewefwefwefqewfwef,ER zijn geentoads.,Muzhroomzzz,datum 1,datum 2,datum 3,https://toad.com,5
2,mario is coolL,Geen Toad,Mario,Toad-001,zoeken,fewefwefwefqewfwef,ER zijn geentoads.,Muzhroomzzz,datum 1,datum 2,datum 3,https://toad.com,6
3,mario is coolL,Geen Toad,Mario,Toad-001,ACX,XXC,ER zijn geentoads.,Muzhroomzzz,datum 1,datum 2,datum 3,https://toad.com,7

In [41]:
%%sql
            SELECT Functie.functie_naam, Status.status, Begrippenkader.naam_begrippenkader, Begrip_code.code,
                   Begrip.voorkeursterm, Begrip.definitie_begrip,  Begrip.toelichting_begrip,
                   Begrip.voorbeeld_begrip, Begrip.aangemaakt_op, Begrip.gewijzigd_op, Begrip.vervalt_op, Begrip.bron,
                   Begrip.begrip_id
            FROM Begrip
            JOIN Functie ON Functie.functie_id = Begrip.FK_functie_id
            JOIN Status ON Status.status_id = Begrip.FK_status_id
            JOIN Begrippenkader ON Begrippenkader.begrippenkader_id = Begrip.FK_begrippenkader_id
            JOIN Begrip_code ON Begrip_code.begrip_code_id = Begrip.FK_begrip_code_id
            WHERE Begrippenkader.naam_begrippenkader = "Yoshi" AND Begrip.voorkeursterm = "BowserisToad"
            ORDER BY Begrip.begrip_id

,functie_naam,status,naam_begrippenkader,code,voorkeursterm,definitie_begrip,toelichting_begrip,voorbeeld_begrip,aangemaakt_op,gewijzigd_op,vervalt_op,bron,begrip_id
0,mario is coolL,Geen Toad,Yoshi,Toad-001,BowserisToad,bowser,Bowser Bowser Bowser Bowser,Buzzhe,datum 1,datum 2,datum 3,https://toad.com,9

In [53]:
%%sql
            SELECT Alternatieve_term.alternatieve_term_id, Begrip.voorkeursterm, Status.status, Functie.functie_naam,
                   Begrippenkader.naam_begrippenkader, Alternatieve_term.alternatieve_term,Alternatieve_term.aangemaakt_op, Alternatieve_term.gewijzigd_op,
                   Alternatieve_term.vervalt_op
            FROM Alternatieve_term
            JOIN Begrip ON Begrip.begrip_id = Alternatieve_term.FK_begrip_id
            JOIN Status ON Status.status_id = Alternatieve_term.FK_status_id
            JOIN Functie ON Functie.functie_id = Alternatieve_term.FK_functie_id
            JOIN Begrippenkader ON Begrippenkader.begrippenkader_id = Alternatieve_term.FK_begrippenkader_id

            WHERE Begrippenkader.naam_begrippenkader = "Yoshi" AND Begrip.voorkeursterm = "BowserisToad"
            ORDER BY Begrip.begrip_id

,alternatieve_term_id,voorkeursterm,status,functie_naam,naam_begrippenkader,alternatieve_term,aangemaakt_op,gewijzigd_op,vervalt_op
0,5,BowserisToad,Geen Toad,mario is coolL,Yoshi,B1,FDDEF,CFR,CCE
1,6,BowserisToad,Geen Toad,mario is coolL,Yoshi,B2,FDDEF,CFR,CCE
2,7,BowserisToad,Geen Toad,mario is coolL,Yoshi,C1,FDDEF,CFR,CCE
3,8,BowserisToad,Geen Toad,mario is coolL,Yoshi,AA4,FDDEF,CFR,CCE
4,9,BowserisToad,Geen Toad,mario is coolL,Yoshi,AA5,FDDEF,CFR,CCE

In [8]:
%%sql
SELECT strftime('%Y-%m-%dT%H:%M:%SZ', 'now');

  strftime('%Y-%m-%dT%H:%M:%SZ', 'now')
0                  2026-06-29T13:49:03Z

In [3]:
query_resultaat = stormrg.ID_zoekBegrip(
    {
        "begrip_id": 1
    }
)

query_resultaat

[{'begrip_id': 1,
  'functie_naam': 'mario is coolL',
  'status_naam': 'Toad',
  'naam_begrippenkader': 'Toadjes_zijnCool',
  'begrip_code': 'Toad-001',
  'voorkeursterm': '1E voorkeursterm',
  'definitie_begrip': 'Uitleg ............... effwefqefwefwefqewfwef',
  'toelichting_begrip': 'toelichting_begrip ..........',
  'voorbeeld_begrip': 'voorbeeld_begrip . biorboiqhrebo qreoqierjgoiqerg',
  'aangemaakt_op': 'datum 1',
  'gewijzigd_op': 'datum 2',
  'vervalt_op': 'datum 3',
  'bron': 'https://toad.com'}]